### ISSUE TITLE
No field `link_role` on type `esp_ble_gatts_cb_param_t_gatts_disconnect_evt_param`

### ISSUE THREAD

**Issue by cwoolum** [pulse-loop/bluedroid#6]
After getting `0.3.5`, I'm no longer able to compile. I get the following error message.

```
   Compiling bluedroid v0.3.6
error[E0609]: no field `link_role` on type `esp_ble_gatts_cb_param_t_gatts_disconnect_evt_param`
  --> C:\Users\slick\.cargo\registry\src\github.com-1ecc6299db9ec823\bluedroid-0.3.6\src\utilities\connection.rs:27:29
   |
27 |             is_slave: param.link_role == 1,
   |                             ^^^^^^^^^ unknown field
   |
   = note: available fields are: `conn_id`, `remote_bda`, `reason`

For more information about this error, try `rustc --explain E0609`.
```

I'm guessing some dependency of mine changed and is no longer compatible? 

These are my dependencies

```
esp-idf-sys = { version = "^0.31.10", features = ["native"] }
esp-idf-svc = { version = "0.43.4" }
embedded-svc = { version = "0.23.1" }
log = { version = "0.4.17" }
lazy_static = { version = "1.4.0" }
```

**Comment by cwoolum** [comment]
Turns out I was compiling with V5 of ESP-IDF. Looks like the params changed for `gatts_disconnect_evt_param`.

https://docs.espressif.com/projects/esp-idf/en/v4.4.3/esp32/api-reference/bluetooth/esp_gatts.html#_CPPv4N24esp_ble_gatts_cb_param_t26gatts_disconnect_evt_paramE

**Comment by persello** [comment]
Will keep this in mind when a migration is needed. As of now, I plan on simply updating the crate at the same pace of the other hardware access crates of esp-rs. Unfortunately, backwards compatibility won't be possible as their API is not stable, as you can see from the latest pull request.
